namespace KF.Monitoring.Contracts.EventReader;

public sealed record EventReaderFasterStoreStatsDto(
    DateTimeOffset Timestamp,
    IReadOnlyDictionary<string, long> BacklogByShard,
    IReadOnlyDictionary<string, long> BacklogByModel,
    IReadOnlyDictionary<string, string> ActiveModelVersions,
    double OldestBacklogAgeSeconds,
    string StorePath,
    string CheckpointPath,
    string LeasePath,
    long StoreDirectorySizeBytes,
    long CheckpointDirectorySizeBytes,
    long LeaseDirectorySizeBytes,
    long AvailableDiskBytes,
    long EnqueuedTotal,
    double EnqueuedRatePerSecond,
    long ShardLeaseTotal,
    double ShardLeaseRatePerSecond,
    long OutputLeaseTotal,
    double OutputLeaseRatePerSecond,
    long CompletedTotal,
    double CompletedRatePerSecond,
    long RetryTotal,
    double RetryRatePerSecond,
    long FailedTotal,
    double FailedRatePerSecond,
    long SuppressedTotal,
    double SuppressedRatePerSecond,
    long CheckpointCount,
    DateTimeOffset? LastCheckpointTime,
    double LastCheckpointDurationMs,
    double AverageProcessingLatencyMs,
    double P95ProcessingLatencyMs,
    double AverageQueueLatencyMs,
    double P95QueueLatencyMs,
    long CleanupTotal,
    double CleanupRatePerSecond,
    DateTimeOffset? LastCleanupTime,
    long StaleRecoveryTotal,
    double StaleRecoveryRatePerSecond,
    DateTimeOffset? LastStaleRecoveryTime);
